# CONFIG FILE FOR PROJECT CONSTANTS

WIDTH = 620
HEIGHT = 460
SCREEN_SIZE = f"{WIDTH}x{HEIGHT}"
TITLE = "YouTube Video Downloader"

DOWNLOAD_OPTION_1_VIDEO_MP4 = "Video as .mp4"
DOWNLOAD_OPTION_2_VIDEO_MP3 = "Video as .mp3"
DOWNLOAD_OPTION_3_PLAYLIST_MP4 = "Playlist as .mp4's"
DOWNLOAD_OPTION_4_PLAYLIST_MP3 = "Playlist as .mp3's"
DOWNLOAD_OPTIONS = [DOWNLOAD_OPTION_1_VIDEO_MP4,
                    DOWNLOAD_OPTION_2_VIDEO_MP3,
                    DOWNLOAD_OPTION_3_PLAYLIST_MP4,
                    DOWNLOAD_OPTION_4_PLAYLIST_MP3]

VERDANT_GREEN = "#00F904"
